-- InternMatch AI — Gate 2.3 Synthetic Demo Dataset Seed
-- Target Tables: public.skills, public.internship_listings
-- Idempotency Strategy: Fixed Deterministic UUIDs with ON CONFLICT DO NOTHING / UPDATE
-- Provenance: 100% Synthetic Original Demo Data (No real data or web scraping)

-- ============================================================
-- 1. SEED MASTER SKILLS TAXONOMY
-- ============================================================

INSERT INTO public.skills (id, name, category) VALUES
  ('10000000-0000-0000-0000-000000000001', 'Python', 'Programming Languages'),
  ('10000000-0000-0000-0000-000000000002', 'FastAPI', 'Backend Frameworks'),
  ('10000000-0000-0000-0000-000000000003', 'PostgreSQL', 'Databases'),
  ('10000000-0000-0000-0000-000000000004', 'Docker', 'DevOps & Containers'),
  ('10000000-0000-0000-0000-000000000005', 'Redis', 'Caching & Queues'),
  ('10000000-0000-0000-0000-000000000006', 'PyTorch', 'AI & Machine Learning'),
  ('10000000-0000-0000-0000-000000000007', 'Scikit-Learn', 'AI & Machine Learning'),
  ('10000000-0000-0000-0000-000000000008', 'Pandas', 'Data Science'),
  ('10000000-0000-0000-0000-000000000009', 'React', 'Frontend Frameworks'),
  ('10000000-0000-0000-0000-000000000010', 'TypeScript', 'Programming Languages'),
  ('10000000-0000-0000-0000-000000000011', 'React Native', 'Mobile Development'),
  ('10000000-0000-0000-0000-000000000012', 'Expo', 'Mobile Development'),
  ('10000000-0000-0000-0000-000000000013', 'Kubernetes', 'DevOps & Cloud'),
  ('10000000-0000-0000-0000-000000000014', 'AWS', 'Cloud Infrastructure'),
  ('10000000-0000-0000-0000-000000000015', 'Cybersecurity', 'Security'),
  ('10000000-0000-0000-0000-000000000016', 'Go', 'Programming Languages'),
  ('10000000-0000-0000-0000-000000000017', 'Rust', 'Programming Languages'),
  ('10000000-0000-0000-0000-000000000018', 'Java', 'Programming Languages'),
  ('10000000-0000-0000-0000-000000000019', 'Spring Boot', 'Backend Frameworks'),
  ('10000000-0000-0000-0000-000000000020', 'Swift', 'Mobile Development'),
  ('10000000-0000-0000-0000-000000000021', 'Kotlin', 'Mobile Development'),
  ('10000000-0000-0000-0000-000000000022', 'C++', 'Programming Languages'),
  ('10000000-0000-0000-0000-000000000023', 'GraphQL', 'API & Data'),
  ('10000000-0000-0000-0000-000000000024', 'Apache Spark', 'Big Data'),
  ('10000000-0000-0000-0000-000000000025', 'LLM Prompt Engineering', 'AI & GenAI')
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- 2. SEED CONTROLLED SYNTHETIC INTERNSHIP LISTINGS (35 LISTINGS)
-- ============================================================

INSERT INTO public.internship_listings (
    id, title, company, location, work_type, description,
    required_skills, preferred_skills, language, education_requirements, experience_requirements, metadata
) VALUES
  (
    '20000000-0000-0000-0000-000000000001',
    'Backend Systems Engineer Intern',
    'CloudScale Technologies',
    'Remote',
    'remote',
    'Join our cloud infrastructure team building high-throughput RESTful APIs and microservices. You will work on Python backend components, database optimization, and Redis task queues in a modern containerized environment.',
    ARRAY['Python', 'FastAPI', 'PostgreSQL'],
    ARRAY['Docker', 'Redis', 'AWS'],
    'English',
    'Bachelor degree student in Computer Science, Software Engineering, or related STEM field.',
    'Prior coursework or personal project experience with Python backend frameworks.',
    '{"stipend": "$35/hr", "duration": "12 weeks", "department": "Backend Infrastructure"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    'AI Research & Machine Learning Intern',
    'NexaAI Solutions',
    'Remote',
    'remote',
    'Work alongside senior AI scientists fine-tuning open-source LLMs, building retrieval-augmented generation (RAG) pipelines, and conducting experiment evaluations for enterprise AI software.',
    ARRAY['Python', 'PyTorch', 'Scikit-Learn'],
    ARRAY['LLM Prompt Engineering', 'Pandas', 'Docker'],
    'English',
    'Enrolled in BS/MS program in Computer Science, Artificial Intelligence, or Data Science.',
    'Familiarity with deep learning frameworks and basic NLP concepts.',
    '{"stipend": "$40/hr", "duration": "12 weeks", "department": "AI Research"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000003',
    'Data Science & Analytics Intern',
    'QuantumData Systems',
    'San Francisco, CA',
    'hybrid',
    'Analyze large-scale tabular datasets, build statistical forecast models, and create automated data pipeline reporting dashboards to drive product growth insights.',
    ARRAY['Python', 'SQL', 'Pandas'],
    ARRAY['Scikit-Learn', 'PostgreSQL', 'Docker'],
    'English',
    'Degree candidate in Data Science, Statistics, Mathematics, or Computer Science.',
    'Hands-on experience with SQL queries and Python data analysis libraries.',
    '{"stipend": "$38/hr", "duration": "10 weeks", "department": "Data Analytics"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000004',
    'Mobile App Developer Intern (React Native)',
    'ApexMobile Labs',
    'Austin, TX',
    'hybrid',
    'Help craft slick, responsive cross-platform mobile user interfaces using React Native and Expo. You will collaborate closely with product designers to implement smooth UI interactions and offline storage.',
    ARRAY['TypeScript', 'React Native', 'Expo'],
    ARRAY['React', 'GraphQL', 'Docker'],
    'English',
    'BS student in Computer Science, Human-Computer Interaction, or Software Engineering.',
    'Experience building React or React Native frontend mobile components.',
    '{"stipend": "$36/hr", "duration": "12 weeks", "department": "Mobile Frontend"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000005',
    'Cybersecurity & SecOps Analyst Intern',
    'CyberShield Defense',
    'Boston, MA',
    'onsite',
    'Participate in vulnerability audits, secure code reviews, and threat monitoring across our cloud infrastructure. Learn identity security standards and automated compliance testing.',
    ARRAY['Cybersecurity', 'Python', 'AWS'],
    ARRAY['Docker', 'PostgreSQL'],
    'English',
    'Degree student in Cybersecurity, Computer Science, or Information Security.',
    'Understanding of web security fundamentals (OWASP Top 10, JWT, TLS).',
    '{"stipend": "$37/hr", "duration": "12 weeks", "department": "Security Operations"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000006',
    'Cloud Infrastructure & DevOps Intern',
    'DevStack Dynamics',
    'Remote',
    'remote',
    'Assist in automating CI/CD build pipelines, configuring Docker container deployments, and monitoring Kubernetes cluster metrics for cloud-native web services.',
    ARRAY['Docker', 'AWS', 'Python'],
    ARRAY['Kubernetes', 'PostgreSQL', 'Redis'],
    'English',
    'Computer Science or Computer Engineering student.',
    'Familiarity with Linux command line tools and basic Docker containerization.',
    '{"stipend": "$35/hr", "duration": "12 weeks", "department": "DevOps & Cloud"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000007',
    'Full Stack Software Engineer Intern',
    'FrontTier Web Studio',
    'New York, NY',
    'hybrid',
    'Contribute across our web stack by building Next.js web applications, integrating backend FastAPI microservices, and writing clean, tested TypeScript components.',
    ARRAY['TypeScript', 'React', 'Python'],
    ARRAY['FastAPI', 'PostgreSQL', 'Docker'],
    'English',
    'BS/MS student in Software Engineering or Computer Science.',
    'Demonstrable personal or academic full-stack web project portfolio.',
    '{"stipend": "$38/hr", "duration": "12 weeks", "department": "Engineering"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000008',
    'Frontend Developer Intern (React / TypeScript)',
    'FrontTier Web Studio',
    'Remote',
    'remote',
    'Focus on frontend user interfaces, accessible design components, and state management. Work with modern UI design systems and stateful React applications.',
    ARRAY['TypeScript', 'React'],
    ARRAY['Expo', 'GraphQL'],
    'English',
    'Computer Science, Web Development, or Interactive Media student.',
    'Solid foundation in HTML/CSS, JavaScript/TypeScript, and React component design.',
    '{"stipend": "$34/hr", "duration": "10 weeks", "department": "Frontend Engineering"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000009',
    'NLP & LLM Systems Engineer Intern',
    'NexaAI Solutions',
    'Remote',
    'remote',
    'Design semantic text search indexes, benchmark embedding vector similarity algorithms, and optimize prompt templates for generative AI text applications.',
    ARRAY['Python', 'PyTorch', 'LLM Prompt Engineering'],
    ARRAY['PostgreSQL', 'Redis', 'FastAPI'],
    'English',
    'Enrolled in Computer Science, Data Science, or Computational Linguistics degree.',
    'Experience working with text embeddings and language model API interfaces.',
    '{"stipend": "$42/hr", "duration": "12 weeks", "department": "AI Applied Engineering"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000010',
    'Database Engineering & SQL Analyst Intern',
    'QuantumData Systems',
    'Chicago, IL',
    'onsite',
    'Optimize complex relational database schemas, write analytical SQL queries, tune index performance, and assist in maintaining PostgreSQL database clusters.',
    ARRAY['PostgreSQL', 'Python'],
    ARRAY['Docker', 'Redis', 'AWS'],
    'English',
    'BS student in Computer Science or Information Technology.',
    'Strong SQL skills (joins, indexes, transactions, aggregations).',
    '{"stipend": "$36/hr", "duration": "12 weeks", "department": "Database Operations"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000011',
    'iOS Mobile Engineering Intern (Swift)',
    'MobileCraft Studios',
    'Seattle, WA',
    'hybrid',
    'Develop high-performance native iOS mobile applications in Swift. Work on smooth UI layouts, local data caching, and asynchronous network integration.',
    ARRAY['Swift', 'TypeScript'],
    ARRAY['React Native', 'GraphQL'],
    'English',
    'Computer Science or Software Engineering student.',
    'Understanding of iOS app architecture and Swift language fundamentals.',
    '{"stipend": "$37/hr", "duration": "12 weeks", "department": "iOS Engineering"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000012',
    'Android App Developer Intern (Kotlin)',
    'MobileCraft Studios',
    'Remote',
    'remote',
    'Build native Android smartphone applications using Kotlin and Jetpack Compose. Implement clean architecture principles and REST API clients.',
    ARRAY['Kotlin', 'TypeScript'],
    ARRAY['React Native', 'Docker'],
    'English',
    'Software Engineering or Computer Science student.',
    'Experience with Kotlin or Java development on the Android platform.',
    '{"stipend": "$35/hr", "duration": "10 weeks", "department": "Android Engineering"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000013',
    'Application Security & Pen Testing Intern',
    'CyberShield Defense',
    'Remote',
    'remote',
    'Conduct automated security scans on REST APIs, review application source code for security flaws, and document remediation guidelines for development teams.',
    ARRAY['Cybersecurity', 'Python'],
    ARRAY['Docker', 'FastAPI'],
    'English',
    'Cybersecurity or Information Assurance student.',
    'Familiarity with web application vulnerability assessment tools.',
    '{"stipend": "$38/hr", "duration": "12 weeks", "department": "Application Security"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000014',
    'Distributed Systems & Rust Engineering Intern',
    'Distributed Cloud Systems',
    'Remote',
    'remote',
    'Write ultra-low-latency distributed storage and network communication components in Rust. Benchmark memory safety, concurrency, and async networking routines.',
    ARRAY['Rust', 'C++'],
    ARRAY['Docker', 'Kubernetes'],
    'English',
    'Computer Science, Computer Systems, or Mathematics student.',
    'Proficiency in systems programming languages (Rust or C++).',
    '{"stipend": "$43/hr", "duration": "12 weeks", "department": "Core Systems"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000015',
    'FinTech API Developer Intern (Go / Microservices)',
    'FinTech Core Labs',
    'Charlotte, NC',
    'onsite',
    'Engineer fault-tolerant payment transaction microservices using Go. Learn event-driven architecture, distributed caching, and microservice orchestration.',
    ARRAY['Go', 'PostgreSQL'],
    ARRAY['Docker', 'Redis', 'AWS'],
    'English',
    'Computer Science, Finance Engineering, or Software Systems candidate.',
    'Experience writing backend HTTP services in Go, Python, or Java.',
    '{"stipend": "$39/hr", "duration": "12 weeks", "department": "FinTech Backend"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000016',
    'Machine Learning Operations (MLOps) Intern',
    'NexaAI Solutions',
    'Remote',
    'remote',
    'Automate model training workflows, set up model tracking artifacts, and manage containerized AI model inference servers on AWS cloud infrastructure.',
    ARRAY['Python', 'Docker', 'AWS'],
    ARRAY['PyTorch', 'Kubernetes', 'Redis'],
    'English',
    'Computer Science, Systems Engineering, or Data Engineering student.',
    'Understanding of container deployment and basic machine learning lifecycles.',
    '{"stipend": "$39/hr", "duration": "12 weeks", "department": "ML Platform"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000017',
    'Computer Vision & Graphics Engineer Intern',
    'Visionary AI Research',
    'San Jose, CA',
    'hybrid',
    'Develop computer vision algorithms for real-time video stream detection, spatial tracking, and image feature extraction using PyTorch and OpenCV.',
    ARRAY['Python', 'C++', 'PyTorch'],
    ARRAY['Scikit-Learn', 'Docker'],
    'English',
    'Enrolled in BS/MS/PhD in Computer Vision, Robotics, or Electrical Engineering.',
    'Experience with image processing libraries and deep learning vision models.',
    '{"stipend": "$41/hr", "duration": "12 weeks", "department": "Vision Research"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000018',
    'Site Reliability Engineering (SRE) Intern',
    'CloudScale Technologies',
    'Remote',
    'remote',
    'Monitor platform uptime, write telemetry alert scripts, analyze latency bottlenecks, and participate in blameless post-mortem incident reviews.',
    ARRAY['Python', 'Docker', 'AWS'],
    ARRAY['Kubernetes', 'Redis'],
    'English',
    'Systems Engineering, Computer Science, or DevOps student.',
    'Scripting skills in Python or Bash, plus basic cloud platform exposure.',
    '{"stipend": "$36/hr", "duration": "10 weeks", "department": "Site Reliability"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000019',
    'Data Engineering Pipeline Intern (Spark / Kafka)',
    'EcoSmart Analytics',
    'Denver, CO',
    'hybrid',
    'Build distributed ETL data pipelines using PySpark and Apache Kafka. Ingest IoT telemetry streams into PostgreSQL and cloud data warehouses.',
    ARRAY['Python', 'Apache Spark', 'PostgreSQL'],
    ARRAY['Docker', 'AWS', 'Pandas'],
    'English',
    'Data Engineering, Computer Science, or Information Systems student.',
    'Experience writing data transformation scripts and working with SQL databases.',
    '{"stipend": "$37/hr", "duration": "12 weeks", "department": "Data Engineering"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000020',
    'BioTech Data Analyst Intern',
    'BioHealth Digital',
    'Remote',
    'remote',
    'Analyze biomedical research datasets, generate automated statistical summary reports, and assist clinical research teams with data data cleaning.',
    ARRAY['Python', 'Pandas', 'Scikit-Learn'],
    ARRAY['PostgreSQL', 'Docker'],
    'English',
    'Bioinformatics, Data Science, or Biostatistics student.',
    'Python data wrangling experience (Pandas, NumPy, Matplotlib/Seaborn).',
    '{"stipend": "$35/hr", "duration": "12 weeks", "department": "BioInformatics"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000021',
    'UI/UX Product Design & Engineering Intern',
    'ApexMobile Labs',
    'Los Angeles, CA',
    'hybrid',
    'Bridge product design and mobile development by designing interactive UI prototypes and converting Figma wireframes into React Native mobile components.',
    ARRAY['TypeScript', 'React Native'],
    ARRAY['Expo', 'React'],
    'English',
    'Design, HCI, or Software Development degree student.',
    'Proficiency in Figma and introductory JavaScript/React Native skills.',
    '{"stipend": "$33/hr", "duration": "10 weeks", "department": "Product Experience"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000022',
    'Embedded Systems & IoT Hardware Intern',
    'EcoSmart Analytics',
    'Detroit, MI',
    'onsite',
    'Write low-level firmware in C/C++ for microcontroller sensors. Test sensor wireless protocols and collect hardware diagnostics.',
    ARRAY['C++', 'Python'],
    ARRAY['Cybersecurity', 'Docker'],
    'English',
    'Electrical Engineering, Computer Engineering, or Embedded Systems student.',
    'Experience with C/C++ microcontrollers (Arduino, STM32, or ESP32).',
    '{"stipend": "$35/hr", "duration": "12 weeks", "department": "Hardware Engineering"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000023',
    'Blockchain & Smart Contract Developer Intern',
    'FinTech Core Labs',
    'Remote',
    'remote',
    'Audit smart contract code, write automated testing suites for decentralized financial primitives, and research cryptographic verification techniques.',
    ARRAY['TypeScript', 'Rust'],
    ARRAY['Go', 'Cybersecurity'],
    'English',
    'Computer Science or Cryptography student.',
    'Understanding of blockchain ledger concepts and smart contract development.',
    '{"stipend": "$40/hr", "duration": "12 weeks", "department": "Decentralized Tech"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000024',
    'QA Automation & Test Infrastructure Intern',
    'DevStack Dynamics',
    'Remote',
    'remote',
    'Write automated end-to-end integration tests for web APIs and mobile apps. Build test execution harnesses for continuous integration pipelines.',
    ARRAY['Python', 'TypeScript'],
    ARRAY['FastAPI', 'Docker', 'React Native'],
    'English',
    'Computer Science, Software Testing, or Quality Engineering student.',
    'Scripting experience in Python or JavaScript and interest in software QA automation.',
    '{"stipend": "$33/hr", "duration": "10 weeks", "department": "Quality Assurance"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000025',
    'Data Visualization & Dashboard Intern',
    'EcoSmart Analytics',
    'Remote',
    'remote',
    'Transform complex metrics into intuitive interactive data visual dashboards. Build custom chart widgets and connect live API data feeds.',
    ARRAY['TypeScript', 'React'],
    ARRAY['Python', 'Pandas'],
    'English',
    'Data Visualization, Computer Science, or Graphic Communication student.',
    'Proficiency in React and web data plotting libraries.',
    '{"stipend": "$34/hr", "duration": "12 weeks", "department": "Analytics UI"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000026',
    'Microservices & Kubernetes Intern',
    'Distributed Cloud Systems',
    'Atlanta, GA',
    'hybrid',
    'Configure service mesh networking, package containerized application services, and manage Kubernetes ingress routing across multi-cloud environments.',
    ARRAY['Docker', 'Kubernetes', 'Go'],
    ARRAY['AWS', 'Python'],
    'English',
    'Cloud Computing or Computer Science student.',
    'Hands-on experience with Linux administration and Docker containers.',
    '{"stipend": "$37/hr", "duration": "12 weeks", "department": "Cloud Platform"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000027',
    'Technical Product Management Intern',
    'ApexMobile Labs',
    'Remote',
    'remote',
    'Write technical feature requirements, coordinate agile sprint backlogs, analyze user analytics metrics, and conduct competitor feature benchmarks.',
    ARRAY['TypeScript', 'Python'],
    ARRAY['React Native', 'PostgreSQL'],
    'English',
    'Technology Management, CS + Business, or Information Systems student.',
    'Strong analytical communication skills and technical software awareness.',
    '{"stipend": "$34/hr", "duration": "12 weeks", "department": "Product Management"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000028',
    'Cloud Security & Compliance Intern',
    'CyberShield Defense',
    'Washington, DC',
    'hybrid',
    'Audit AWS IAM security policies, evaluate automated cloud compliance checks (SOC2, HIPAA), and remediate security posture alerts.',
    ARRAY['Cybersecurity', 'AWS', 'Python'],
    ARRAY['Docker', 'PostgreSQL'],
    'English',
    'Cybersecurity Policy, Information Assurance, or CS candidate.',
    'Knowledge of cloud security fundamentals and identity management.',
    '{"stipend": "$38/hr", "duration": "12 weeks", "department": "Cloud Governance"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000029',
    'High-Performance Computing Intern (C++)',
    'Distributed Cloud Systems',
    'Remote',
    'remote',
    'Optimize memory alignment, SIMD vector instructions, and multi-threaded parallel computation loops for mathematical simulation software.',
    ARRAY['C++', 'Python'],
    ARRAY['Rust', 'Docker'],
    'English',
    'Computer Science, Parallel Computing, or Physics student.',
    'Strong command of modern C++ (C++17/20) and memory management.',
    '{"stipend": "$41/hr", "duration": "12 weeks", "department": "HPC Systems"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000030',
    'Deep Learning Frameworks Intern (PyTorch)',
    'Visionary AI Research',
    'Remote',
    'remote',
    'Implement custom neural network layers, optimize GPU memory consumption, and profile model inference speed across edge devices.',
    ARRAY['Python', 'PyTorch'],
    ARRAY['Scikit-Learn', 'C++'],
    'English',
    'MS/PhD student in Computer Science, Machine Learning, or Computational Mathematics.',
    'Solid background in linear algebra, deep learning architectures, and PyTorch.',
    '{"stipend": "$42/hr", "duration": "12 weeks", "department": "Framework R&D"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000031',
    'Enterprise Java Systems Intern (Spring Boot)',
    'FinTech Core Labs',
    'Dallas, TX',
    'onsite',
    'Develop scalable enterprise banking web services using Java and Spring Boot. Learn message queue integration and database transaction handling.',
    ARRAY['Java', 'Spring Boot', 'PostgreSQL'],
    ARRAY['Docker', 'Redis'],
    'English',
    'Computer Science or Software Engineering student.',
    'Proficiency in Java object-oriented programming and basic SQL databases.',
    '{"stipend": "$36/hr", "duration": "12 weeks", "department": "Enterprise Systems"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000032',
    'Web Performance & Accessibility Intern',
    'FrontTier Web Studio',
    'Remote',
    'remote',
    'Audit web application core web vitals, optimize image rendering assets, and implement WCAG 2.1 accessibility standards across frontend web pages.',
    ARRAY['TypeScript', 'React'],
    ARRAY['Expo'],
    'English',
    'Web Development, HCI, or Computer Science student.',
    'Passion for web accessibility, semantic HTML, and performance tuning.',
    '{"stipend": "$33/hr", "duration": "10 weeks", "department": "Web Standards"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000033',
    'Edge Computing & IoT Cloud Intern',
    'BioHealth Digital',
    'Raleigh, NC',
    'hybrid',
    'Connect edge IoT medical monitor devices to cloud telemetry APIs. Write resilient retry logic, offline data queuing, and local buffer management.',
    ARRAY['Python', 'FastAPI', 'Docker'],
    ARRAY['Redis', 'PostgreSQL'],
    'English',
    'Computer Engineering, IoT, or Software Systems candidate.',
    'Understanding of networking protocols (MQTT, HTTP) and Python backend services.',
    '{"stipend": "$36/hr", "duration": "12 weeks", "department": "Edge Telemetry"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000034',
    'Search & Vector Retrieval Engineering Intern',
    'NexaAI Solutions',
    'Remote',
    'remote',
    'Tune pgvector HNSW indexing strategies, evaluate hybrid keyword + vector search ranking metrics, and build search latency benchmarking suites.',
    ARRAY['Python', 'PostgreSQL', 'FastAPI'],
    ARRAY['Redis', 'Docker', 'LLM Prompt Engineering'],
    'English',
    'Computer Science or Information Retrieval student.',
    'Familiarity with vector databases, SQL query optimization, and Python search tools.',
    '{"stipend": "$40/hr", "duration": "12 weeks", "department": "Search Platform"}'::jsonb
  ),
  (
    '20000000-0000-0000-0000-000000000035',
    'Digital Health Data Security Intern',
    'BioHealth Digital',
    'Remote',
    'remote',
    'Conduct HIPAA data privacy audits, design row-level encryption routines for sensitive patient health records, and write security policy documentation.',
    ARRAY['Cybersecurity', 'Python', 'PostgreSQL'],
    ARRAY['AWS', 'Docker'],
    'English',
    'Cybersecurity, Health Informatics, or CS student.',
    'Interest in health tech data privacy, compliance auditing, and secure database design.',
    '{"stipend": "$36/hr", "duration": "12 weeks", "department": "Health Compliance"}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    company = EXCLUDED.company,
    location = EXCLUDED.location,
    work_type = EXCLUDED.work_type,
    description = EXCLUDED.description,
    required_skills = EXCLUDED.required_skills,
    preferred_skills = EXCLUDED.preferred_skills,
    language = EXCLUDED.language,
    education_requirements = EXCLUDED.education_requirements,
    experience_requirements = EXCLUDED.experience_requirements,
    metadata = EXCLUDED.metadata;
